version: "3.8"

networks:
  dev:
    driver: bridge

services:

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - dev


  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - dev

  pg:
    image: postgres:16.4
    environment:
      POSTGRES_DB: UserYDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      PGDATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d UserYDB"]
      interval: 5s
      timeout: 3s
      retries: 5

  backend:
    ports:
      - 8000:8000
    build:
      context: ./
    networks:
      - dev
    depends_on:
      pg:
        condition: service_healthy
      rabbitmq:
        condition: service_started  # <-- Ждём, пока RabbitMQ запустится
    environment:
      DATABASE_URL: "postgresql+asyncpg://postgres:admin123@pg:5432/UserYDB"
      RMQ_URL: "amqp://guest:guest@rabbitmq:5672/"

      REDIS_HOST: "redis"
      REDIS_PORT: "6379"


    command: >
      /bin/sh -c "alembic upgrade head && uvicorn app.app:app --host 0.0.0.0 --port 8000"
    expose:
      - "8000"


  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    depends_on:
      pg:
        condition: service_healthy
  
  nginx:
    image: nginx:latest
    restart: always
    networks:
      - dev
    depends_on:
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"



volumes:
  pgdata:
